name: emby
url: https://github.com/haberda/emby-addon
version: dev
slug: emby
privileged: 
  - SYS_ADMIN 
  - DAC_READ_SEARCH
arch:
  - aarch64
  - amd64
  - armv7
description: emby media server
startup: system
boot: manual
map: 
  - share:rw
  - media:rw
  - ssl:rw
devices: 
  - /dev/dri
  - /dev/vchiq
  - /dev/video10
  - /dev/video11
  - /dev/video12
ports: 
  8096/tcp: 8096
  8920/tcp: 8920
  33791/tcp: 
  33796/tcp: 
ports_description: 
  8096/tcp: "http webui"
  8920/tcp: "https webui"
  33791/tcp: "external http webui"
  33796/tcp: "external https webui"
schema: 
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  networkdisks: 
    - str?
  cifsusername: str?
  cifspassword: str?
  cifsversion: list(3.0|2.1|2.0|1.0)?
webui: http://[HOST]:[PORT:8096]
backup_exclude:
  - "*/cache/"
  - "*/logs/"
  - "*/transcoding-temp/"
  - "*/metadata/"
init: false
image: ghcr.io/haberda/emby/{arch}
