name: emby
url: https://github.com/haberda/emby-addon
version: dev
slug: emby
arch:
  - aarch64
  - amd64
description: emby media server
map:
  - addon_config:rw
  - share:rw
  - media:rw
devices: 
  - /dev/dri
  - /dev/vchiq
schema: 
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
host_network: true
webui: http://[HOST]:[PORT:8096]
backup_exclude:
  - "*/cache/"
  - "*/logs/"
  - "*/transcoding-temp/"
  - "*/metadata/"
image: ghcr.io/haberda/emby/{arch}
