name: emby
url: https://github.com/haberda/emby-addon
version: 4.9.0.25
slug: emby
arch:
  - amd64
description: emby media server
map:
  - addon_config:rw
  - media:rw
schema: 
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
host_network: true
webui: http://[HOST]:[PORT:8096]
video: true
environment:
  GIDLIST: '28,44,100,103,104,107'
  UID: '0'
  GID: '0'
backup_exclude:
  - "*/cache/"
  - "*/logs/"
  - "*/transcoding-temp/"
  - "*/metadata/"
image: emby/embyserver

