#!/usr/bin/with-contenv bash

# permissions (recursive) on config root and folders
#chown -R abc:abc \
#	/data \
#	/app
# if [ -n "$(ls -A /data 2>/dev/null)" ]; then
# chown abc:abc \
# 	/data/*
# fi
